name: metalprediction
channels:
  - psi4
  - acellera
  - conda-forge
  - omnia
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=11.3
  - pytorch
  - moleculekit
  - ipython
  - rdkit[version='>=2020.09.5']
  - tqdm
  - biopython
  - matplotlib
  - scikit-learn
  - pdb2pqr=3.5.2
  - propka
  - openbabel[version='>=3.1.1']
  - joblib
  - ipykernel
  - py3dmol
